# Generated by Django 3.0.6 on 2021-05-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisteredUser',
            new_name='User',
        ),
        migrations.AddField(
            model_name='seller',
            name='time',
            field=models.CharField(default=7, max_length=10),
            preserve_default=False,
        ),
    ]
